name: hersh-CI
on: [push, pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake -S . -B build
      - name: build
        run: cmake --build build -j2
      - name: test
        run: ctest --test-dir build

